apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/actions-runner-controller/actions-runner-controller
    path: charts/actions-runner-controller
    targetRevision: v0.26.0
    helm:
      parameters:
        - name: syncPeriod
          value: 1m
  destination:
      name: in-cluster
      namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true