apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: linkerd/linkerd-crds
    repoURL: https://helm.linkerd.io/stable
  destination:
      name: in-cluster
      namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true