apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  argocd.argoproj.io/sync-wave: -1
spec:
  project: default
  source:
    repoURL: https://github.com/jordanthomas761/argocd-test
    path: actions-runner-controller/linkerd/
    targetRevision: HEAD
  destination:
      name: in-cluster
      namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true

    
