apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.9.4
    helm:
      parameters:
        - name: identity.issuer.scheme
          value: kubernetes.io/tls
  destination:
      name: in-cluster
      namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true
    - Replace=true