apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system 
---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-workers
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
