apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner-deployment
  namespace: actions-runner-workers
spec:
  template:
    spec:
      repository: jordanthomas761/hello-world-javascript-action