apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: python-runner-deployment
  namespace: actions-runner-workers
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  template:
    spec:
      repository: jordanthomas761/python-test-app     
      dockerdWithinRunnerContainer: false
      dockerdContainerResources:
        limits:
          cpu: "2.0"
          memory: "2Gi"
        requests:
          cpu: "0.25"
          memory: "256Mi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner-deployment
  namespace: actions-runner-workers
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  template:
    spec:
      repository: jordanthomas761/hello-world-javascript-action
      dockerdWithinRunnerContainer: false
      dockerdContainerResources:
        limits:
          cpu: "2.0"
          memory: "2Gi"
        requests:
          cpu: "0.25"
          memory: "256Mi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: actions-runner-workers
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - hello-world-javascript-action
    - python-test-app

