apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner-deployment
spec:
  replicas: 1
  template:
    spec:
      repository: jordanthomas761/hello-world-javascript-action