apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: 0.23.3
    helm:
      parameters:
        - name: syncPeriod
          value: 1m
        - name: runner.statusUpdateHook.enabled
          value: "true"
        - name: "actionsMetricsServer.enabled"
          value: "true"
        - name: "metrics.proxy.enabled"
          value: "false"
        - name: "metrics.serviceMonitor.enable"
          value: "true"
  destination:
      name: in-cluster
      namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true