apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jordanthomas761/argocd-test
    targetRevision: HEAD
    path: website
  destination:
    name: in-cluster
    namespace: personal-site
  helm:
      parameters:
        name: "ref"
        value: $ARGOCD_APP_REVISION
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true
