apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.9.4
    helm:
      # valueFiles:
      #   - values-ha.yaml
      parameters:
        - name: identityTrustAnchorsPEM
          value: |
            -----BEGIN CERTIFICATE-----
            MIIBjTCCATSgAwIBAgIRAL19+mdn949dkNN+DY0B7uwwCgYIKoZIzj0EAwIwJTEj
            MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwNDA1MDEw
            NzAwWhcNMjgwNDAzMDEwNzAwWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
            c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCmYbiMtIqtEiJl/
            eQskvKo4ufr3rcTNnTvytiPkXGyIOJ8RApjhBxfAsdpN48yncikR1ZvzKhtlupwP
            wEIisSijRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
            A1UdDgQWBBTF0IYV/Ubg3QVO3xoDEZwfXtm5JTAKBggqhkjOPQQDAgNHADBEAiAg
            dqKTywyAWLlKSBqfPNJSeHsHd/gFnbls1xj1b/qP2AIgExi2LicbuBQij2m1sFf1
            x+pMDWhHWigsksuVirB5CeM=
            -----END CERTIFICATE-----
        - name: identity.issuer.scheme
          value: kubernetes.io/tls
        - name: proxyInit.runAsRoot
          value: true
  destination:
      name: in-cluster
      namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true
    - Replace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-policy-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-policy-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle