apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javascript-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      parameters:
      - name: runnerScaleSetName
        value: javascript-runner
      - name: githubConfigUrl
        value: https://github.com/jordanthomas761/hello-world-javascript-action
      - name: githubConfigSecret
        value: controller-manager
      - name: controllerServiceAccount.name
        value: actions-runner-controller-gha-rs-controller
      - name: controllerServiceAccount.namespace
        value: arc-system
      - name: Values.containerMode
        value: dind
      valuesObject:
        template:
        template:
          spec:
            tolerations: 
              - key: "purpose"
                operator: "Equal"
                value: "runners" # <----------- Use scalable pool here to scale down/up aggressively without affecting controller or listener
                effect: "NoSchedule"
        listenerTemplate:
          spec:
            containers: # <------------- Without these two lines Helm will refuse applying your values
              - name: listener
            tolerations:
              - key: "CriticalAddonsOnly" # <------------ Use non-scalable node pool here (we use `system` pool in AKS for that)
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"

  destination:
      name: in-cluster
      namespace: actions-runner-workers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true