apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javascript-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      parameters:
      - name: runnerScaleSetName
        value: javascript-runner
      - name: githubConfigUrl
        value: https://github.com/jordanthomas761/hello-world-javascript-action
      - name: githubConfigSecret
        value: controller-manager
      - name: controllerServiceAccount.name
        value: actions-runner-controller-gha-rs-controller
      - name: controllerServiceAccount.namespace
        value: arc-system
      - name: Values.containerMode
        value: dind
      valuesObject:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - pi5-ml

  destination:
      name: in-cluster
      namespace: actions-runner-workers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true