apiVersion: batch/v1
kind: Job
metadata:
  generateName: start-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync, PostSync, SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: mbp-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--header"
          - "Content-type: application/json"
          - "--data"
          - "{\"text\": \"Application {{ .Values.app }} sync is $ARGOCD_APP_NAME \"}"
          - "jordan-mbp.personal-site.svc.cluster.local/webhook"
      restartPolicy: Never
  backoffLimit: 2