kind: Service
apiVersion: v1
metadata:
  name: jordan-mbp
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
---
kind: EndpointSliceEndpointSlice
apiVersion: discovery.k8s.io/v1
metadata:
  name: login-app
  labels:
    kubernetes.io/service-name: jordan-mbp
endpoints:
  - addresses:
    - "10.0.1.114"
ports:
  - port: 8000
    protocol: TCP
