apiVersion: batch/v1
kind: Job
metadata:
  generateName: notify-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: mbp-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--header"
          - "Content-type: application/json"
          - "--data"
          - "{\"text\": \"ArgoCD has synced the website repo\"}"
          - "jordan-mbp/webhook"
      restartPolicy: Never
  backoffLimit: 2